default:
  image: alpine
include:
  - inputs:
      component: control-plane
      deploy_rules: []
      deployment: dev
      rules: []
      stack: cluster
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: control-plane
      deploy_rules: []
      deployment: stg
      rules: []
      stack: cluster
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: node-pools
      deploy_rules: []
      deployment: dev
      rules: []
      stack: cluster
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: node-pools
      deploy_rules: []
      deployment: stg
      rules: []
      stack: cluster
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: postgres
      deploy_rules: []
      deployment: dev
      rules: []
      stack: database
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: postgres
      deploy_rules: []
      deployment: stg
      rules: []
      stack: database
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: redis
      deploy_rules: []
      deployment: dev
      rules: []
      stack: database
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: redis
      deploy_rules: []
      deployment: stg
      rules: []
      stack: database
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: dns
      deploy_rules: []
      deployment: dev
      rules: []
      stack: networking
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: dns
      deploy_rules: []
      deployment: stg
      rules: []
      stack: networking
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: vpc
      deploy_rules: []
      deployment: dev
      rules: []
      stack: networking
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: vpc
      deploy_rules: []
      deployment: stg
      rules: []
      stack: networking
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: alerting
      deploy_rules: []
      deployment: dev
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: alerting
      deploy_rules: []
      deployment: stg
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: logging
      deploy_rules: []
      deployment: dev
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: logging
      deploy_rules: []
      deployment: stg
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: metrics
      deploy_rules: []
      deployment: dev
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: metrics
      deploy_rules: []
      deployment: stg
      rules: []
      stack: observability
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: cert-manager
      deploy_rules: []
      deployment: dev
      rules: []
      stack: platform-services
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: cert-manager
      deploy_rules: []
      deployment: stg
      rules: []
      stack: platform-services
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: ingress
      deploy_rules: []
      deployment: dev
      rules: []
      stack: platform-services
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: ingress
      deploy_rules: []
      deployment: stg
      rules: []
      stack: platform-services
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: certs
      deploy_rules: []
      deployment: dev
      rules: []
      stack: security
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: certs
      deploy_rules: []
      deployment: stg
      rules: []
      stack: security
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: iam
      deploy_rules: []
      deployment: dev
      rules: []
      stack: security
    local: gitlab-templates/profile-tofu/template.yml
  - inputs:
      component: iam
      deploy_rules: []
      deployment: stg
      rules: []
      stack: security
    local: gitlab-templates/profile-tofu/template.yml
stages:
  - main
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
