stack-a:cmp-a:dev:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-a:cmp-a:dev:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-a:cmp-a:stg:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-a:cmp-a:stg:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-a:cmp-a:validate:
  script:
    - echo tofu validate
  stage: main
stack-a:cmp-b:dev:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-a:cmp-b:dev:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-a:cmp-b:stg:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-a:cmp-b:stg:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-a:cmp-b:validate:
  script:
    - echo tofu validate
  stage: main
stack-b:cmp-a:dev:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-b:cmp-a:dev:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-b:cmp-a:stg:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-b:cmp-a:stg:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-b:cmp-a:validate:
  script:
    - echo tofu validate
  stage: main
stack-b:cmp-b:dev:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-b:cmp-b:dev:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-b:cmp-b:stg:deploy:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu deploy
  stage: main
stack-b:cmp-b:stg:plan:
  needs:
    - artifacts: false
      job: stack-a:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-a:stg:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:dev:plan
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:deploy
      optional: true
    - artifacts: false
      job: stack-a:cmp-b:stg:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-a:dev:plan
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:deploy
      optional: true
    - artifacts: false
      job: stack-b:cmp-b:dev:plan
      optional: true
  script:
    - echo tofu plan
  stage: main
stack-b:cmp-b:validate:
  script:
    - echo tofu validate
  stage: main
stages:
  - main
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
