jobs:
  stack-a_cmp-a_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-a_cmp-a_dev_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-a_cmp-a_stg_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-a_cmp-a_stg_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-a_cmp-a_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu validate
  stack-a_cmp-b_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-a_cmp-b_dev_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-a_cmp-b_stg_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-a_cmp-b_stg_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-a_cmp-b_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu validate
  stack-b_cmp-a_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-b_cmp-a_dev_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-b_cmp-a_stg_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-b_cmp-a_stg_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-b_cmp-a_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu validate
  stack-b_cmp-b_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-b_cmp-b_dev_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-b_cmp-b_stg_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu deploy
  stack-b_cmp-b_stg_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu plan
  stack-b_cmp-b_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo tofu validate
name: CI
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
