env:
  COMPONENT: ${{ inputs.component }}
  DEPLOYMENT: ${{ inputs.deployment }}
  STACK: ${{ inputs.stack }}
jobs:
  deploy:
    env:
      NIX_CONFIG: experimental-features = nix-command flakes
      TF_IN_AUTOMATION: "1"
    needs:
      - plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Enter profile
        run: |
          nix print-dev-env .#profile-tofu > profile-tofu.sh
          echo "BASH_ENV=$PWD/profile-tofu.sh" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.stack }}-${{ inputs.component }}-${{ inputs.deployment }}-plan
          path: terraform/${{ env.STACK }}/${{ env.COMPONENT }}
      - run: tofu -chdir=terraform/$STACK/$COMPONENT init -backend-config=deployments/$DEPLOYMENT.tfbackend
      - run: tofu -chdir=terraform/$STACK/$COMPONENT apply -auto-approve tfplan
  plan:
    env:
      NIX_CONFIG: experimental-features = nix-command flakes
      TF_IN_AUTOMATION: "1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.33.0/install
      - name: Enter profile
        run: |
          nix print-dev-env .#profile-tofu > profile-tofu.sh
          echo "BASH_ENV=$PWD/profile-tofu.sh" >> "$GITHUB_ENV"
      - run: tofu -chdir=terraform/$STACK/$COMPONENT init -backend-config=deployments/$DEPLOYMENT.tfbackend
      - run: tofu -chdir=terraform/$STACK/$COMPONENT validate
      - run: tofu -chdir=terraform/$STACK/$COMPONENT plan -var-file=deployments/$DEPLOYMENT.tfvars -out=tfplan
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.stack }}-${{ inputs.component }}-${{ inputs.deployment }}-plan
          path: terraform/${{ env.STACK }}/${{ env.COMPONENT }}/tfplan
          retention-days: 7
"on":
  workflow_call:
    inputs:
      changes:
        description: Change detection JSON passed from the calling workflow.
        type: string
      changes_key:
        description: Key identifying this job in the change detection map.
        type: string
      component:
        description: Component name
        type: string
      deployment:
        description: Deployment name
        type: string
      stack:
        description: Stack name
        type: string
