jobs:
  stack-e_cmp-a_dev_deploy:
    needs:
      - stack-e_cmp-a_dev_plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo tofu deploy
  stack-e_cmp-a_dev_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo tofu plan
"on":
  workflow_call: {}
