jobs:
  stack-c_cmp-b_stg_deploy:
    needs:
      - stack-c_cmp-b_stg_plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo tofu deploy
  stack-c_cmp-b_stg_plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo tofu plan
"on":
  workflow_call: {}
